import NavBar from "../components/NavBar";
import Head from "next/head";
import fetcher from "@/utils/fetcher";
import Card from "../components/Card";
import Link from "next/link";

export default function Home({ only5 }: any) {
  return (
    <>
      <Head>
        <title>YouReadIt?</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar />

      <h1
        style={{
          display: "flex",
          justifyContent: "center",
        }}
      >
        Randoms Quotes
      </h1>
      <div
        style={{ display: "flex", justifyContent: "center", flexWrap: "wrap" }}
      >
        {only5.map((quotes: any) => {
          return <Card key={quotes._id} quotes={quotes} />;
        })}
      </div>
    </>
  );
}

export async function getServerSideProps() {
  try {
    const only5 = await fetcher(`?limit=5`);
    return {
      props: {
        only5,
      },
    };
  } catch (error) {
    console.log(error);
  }
}
