import Head from "next/head";
import fetcher from "@/utils/fetcher";
import Card from "../components/Card";
import { useEffect, useState } from "react";

export interface QuotesTypes {
  _id: string;
  author: string;
  content: string;
  tags: string[];
}

export default function Home({ only5 }: { only5: [] }) {
  const [readyQuotes, setReadyQuotes] = useState<QuotesTypes[]>([]);
  const refreshStorage = () => {
    localStorage.removeItem("quotes");
  };

  useEffect(() => {
    if (localStorage.getItem("quotes") === null) {
      localStorage.setItem("quotes", JSON.stringify(only5));
      setReadyQuotes(only5);
    } else {
      setReadyQuotes(JSON.parse(localStorage.getItem("quotes")!));
    }
  }, [only5]);

  return (
    <>
      <Head>
        <title>YouReadIt?</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1
        style={{
          display: "flex",
          justifyContent: "center",
        }}
      >
        Quotes Of The Day
      </h1>

      <div
        style={{ display: "flex", justifyContent: "center", flexWrap: "wrap" }}
      >
        {readyQuotes.map((quotes: QuotesTypes) => {
          return <Card key={quotes._id} quotes={quotes} />;
        })}
      </div>
    </>
  );
}

export async function getServerSideProps() {
  try {
    const only5: [] = await fetcher(`?limit=5`);
    return {
      props: {
        only5,
      },
    };
  } catch (error) {
    console.log(error);
  }
}
